# Exclude third party code and build artifacts
excluded:
  - Pods/
  - Carthage/
  - build/
  - .build

# Disabled rules that often cause too many initial warnings
disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_cast
  - todo
  - type_body_length
  - cyclomatic_complexity
  - file_length

# Relaxed limits for warnings/errors
file_length:
  warning: 500
  error: 1000

# Reporter configuration
reporter: "xcode"