name: SwiftLint

on:
  pull_request:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint and output JSON
        run: swiftlint --reporter json > swiftlint_output.json
